name = "duolumia"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "BD"
database_name = "bd-clients"
database_id = "6947fa57-e1be-4678-a31b-6cbcbac23ac4"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cliplumia-images"

[[r2_buckets]]
binding = "R2_GENERATIONS_BUCKET"
bucket_name = "cliplumia-generations"

[vars]
GOOGLE_CLIENT_ID = "1018792613471-j52k68g5qm7nrerqrpvqj9d5hkdt7vqe.apps.googleusercontent.com"
